### ISSUE TITLE
How to secure pages?

### ISSUE THREAD

**Issue by cacortina** [devplanete/php-login-advanced#24]
I just tried your script, so far all went fine on installation, but, How to secure my pages? been reading and nothing says how to doit, thanks for your effort on giving us this script, cheers.

**Comment by austinkregel** [comment]
The best way to "Secure" your pages is by making sure there is a logged in user. If there is a user logged in then do your things, if not then redirect them to a login screen. The examples used on the website (to display the login) is the following
```php
if($login->isUserLoggedIn() === true){
  // Do all the things
} else {
  // Do that thing that logs the person in.
}
```
which checks to make sure that there is a logged in user, essentially securing the page.

Other than that as far as security goes, the script uses PDO. PDO protects most people from sql injection (I say most because there is a spesific type of SQL injection that must be preformed for it to work and it's described on [stackoverflow](http://stackoverflow.com/questions/134099/are-pdo-prepared-statements-sufficient-to-prevent-sql-injection)).

If you want something more secure the best thing you can do is either get an [SSL certificate](https://www.globalsign.com/en/ssl-information-center/what-is-an-ssl-certificate/) from [any](https://www.godaddy.com/ssl/ssl-certificates.aspx) [number](https://www.digicert.com/ssl-certificate.htm) [of](https://www.instantssl.com/ssl-certificate.html) [websites](https://www.ssls.com/) (any, number, of , websites, are all different links to seperate websites)
