### ISSUE TITLE
generate unique key

### ISSUE THREAD

**Issue by hagstrand** [devplanete/php-login-advanced#43]
Hello,
Thank you for posting this code.

I see you are using two different techniques for generating a unique key.

1.	hash('sha256', mt_rand());
	For rememberme cookie.  Length 64.
		
2.	sha1(uniqid(mt_rand(), true));
	For email verification for register and reset-password.  Length 40.

Is there some reason for the two different techniques?
Thanks
John

**Comment by austinkregel** [comment]
John,
Though I am not the original author of the package, I would assume that this variation would either be an overlooking of the original coding of the package or it has something to do with the speed of generating the hash. I say this because while in terms of security, both are good enough and hard enough to try to crack to not have to worry about collision. The [sha1 algorithm appears to be 30% faster than sha256](http://crypto.stackexchange.com/questions/15382/hmac-sha1-vs-hmac-sha256) this might be significant because if the site using the script has many requests to generate email verification or reset password hashes and they were to use the algorithm that is slower it would consume more resources and would increase the load on the server.

Whether it's spam or if it's actually people requesting it, having an algorithm that's 30% faster would provider better performance, while having a slow algorithm for generating a cookie that would only be made maybe once, twice, three, for or more times in month depending on what your requirements are would consume less resources as a whole.

I hope this all makes sense and answers your question to a small degree. @panique should be able to answer this in more detail if there is anything more to it.

-Austin Kregel

**Comment by hagstrand** [comment]
Thank your for the thoughtful reply, Austin.  Very helpful.

**Comment by panique** [comment]
He guys, to be honest I don't remember anymore why exactly it was built like that. Maybe the two feature were even coming from different authors, I really cannot say this anymore (it has been 3 years since then).
